import React, { useState } from 'react';
import Content1 from '../Content1/Content1';
import Content2 from '../Content2/Content2';
import './ContentContainer.scss';

const text = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse iaculis ullamcorper nulla, id viverra felis hendrerit id. In hac habitasse platea dictumst. Etiam placerat felis eros, id varius est condimentum in. Vestibulum ornare, ipsum in ultricies tincidunt, turpis eros condimentum leo, et sagittis lectus dui id felis. Maecenas tincidunt orci non metus aliquam, eget egestas ante semper. Proin sed scelerisque lorem. Mauris non velit enim. Curabitur a eros eget enim mollis porttitor quis sit amet turpis. Phasellus pellentesque nisl vitae maximus gravida. Donec ullamcorper nisi eu massa condimentum facilisis. In sit amet blandit ex.
Vivamus imperdiet faucibus mauris, sit amet vestibulum lacus blandit eget. Aenean ac magna felis. Cras venenatis nisi urna, id placerat risus blandit sit amet. Sed id consectetur purus. Proin quam urna, molestie vitae suscipit eget, porta aliquet massa. Fusce fringilla rutrum dolor, at dignissim magna egestas vitae. Morbi et nisi eros. Sed vehicula sagittis aliquet. Nulla commodo dignissim orci eget porttitor. Ut dui enim, commodo eu felis non, bibendum tincidunt turpis. Nam dapibus a urna id tempor. Cras rhoncus ipsum eget justo dapibus euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eleifend auctor vestibulum.
Sed sed urna vitae felis rutrum faucibus. Nam at urna euismod, egestas tellus ac, tincidunt nisl. Nulla metus turpis, dignissim at libero eget, feugiat lobortis velit. Praesent et nulla lorem. Suspendisse potenti. Duis in mauris convallis, aliquet nulla sed, luctus neque. Vivamus vitae felis non lacus maximus ornare non nec ligula. Aenean non scelerisque neque.
Morbi vel congue metus. In rutrum arcu eget dolor ullamcorper, suscipit ultricies lacus feugiat. Maecenas id vestibulum elit. Vestibulum tristique augue arcu, at convallis ex tempor eu. Aenean et euismod augue. Cras laoreet eros eu aliquet dictum. Morbi et justo a leo hendrerit dictum ut nec eros. Donec ultricies sapien at gravida posuere. Phasellus eu fermentum turpis, quis tincidunt nunc.
Etiam placerat lectus turpis, at scelerisque sem ultrices in. Maecenas consectetur ante id pellentesque finibus. Sed ex nunc, faucibus in tristique eu, pretium a nisi. Nulla cursus facilisis magna, eget efficitur nisi pulvinar et. Duis varius magna quis condimentum hendrerit. Integer augue sem, tincidunt sed nisi a, laoreet molestie odio. Etiam non mollis augue, vel placerat lectus. Sed erat nibh, sodales a consectetur vitae, bibendum eget nisi. Praesent quis ligula enim. Pellentesque sollicitudin elit euismod turpis ultrices iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas posuere ipsum sit amet cursus posuere.
Vivamus quis ex enim. Nam sit amet mattis sem. In facilisis ipsum orci, sit amet euismod ipsum commodo vel. Phasellus ultricies erat nunc, convallis cursus magna dictum vel. Nulla dui felis, venenatis sed aliquet in, euismod sed magna. Aliquam ut iaculis neque. Sed vulputate pellentesque leo, id viverra risus sodales sit amet. Donec aliquet consequat augue sed hendrerit. Donec a libero erat. Nullam tristique vitae libero imperdiet fringilla. Aenean viverra odio ut purus imperdiet lobortis. Etiam quis tempor nibh. Cras ornare nisi ligula. Quisque tempus quam vitae dictum porta. Proin vulputate vehicula suscipit. Quisque condimentum arcu eu ante convallis, non egestas dolor suscipit.
Suspendisse quis semper dui. Quisque ac neque eget lectus faucibus pulvinar. Vivamus malesuada rhoncus turpis sed tempor. Praesent egestas nibh in dui blandit, id suscipit sem dictum. Cras eu est massa. Vestibulum sodales venenatis ante, eget consectetur quam commodo at. In dignissim, neque sed porttitor dapibus, sem massa mattis nisl, et gravida neque arcu sit amet elit. In hac habitasse platea dictumst. Sed eget erat ut erat bibendum porta quis et ex. Etiam elementum sagittis augue ac consectetur. Nulla sollicitudin sit amet nibh a convallis. Vestibulum vitae ullamcorper lectus, vitae sagittis arcu. Praesent nulla arcu, laoreet sed lobortis sed, facilisis eget nisi. Morbi massa ante, finibus sit amet convallis sed, vulputate id neque. Etiam lacinia ac ligula non consequat.
Maecenas at libero metus. Proin tristique suscipit turpis, at facilisis ante rhoncus convallis. Donec in libero eu augue vestibulum tempus at vel magna. Etiam cursus eu dolor ut egestas. Pellentesque ullamcorper tellus eu posuere tincidunt. In id purus nec eros maximus gravida quis mattis nunc. Praesent sit amet aliquam velit, malesuada tincidunt lectus. Sed eu erat rhoncus, maximus turpis quis, accumsan turpis. Etiam eget tempor orci. Ut congue est non elit tincidunt venenatis. Phasellus et justo a ligula maximus finibus vel vel justo. Etiam molestie varius mauris vel sagittis.
Suspendisse nec erat commodo, faucibus magna non, laoreet lorem. Ut sem lorem, porttitor sit amet sodales sed, venenatis eget quam. Phasellus sed venenatis sem. Nullam pretium congue nulla a malesuada. Ut maximus consectetur ante vel ultrices. Donec enim velit, porta ut urna eget, lacinia elementum neque. Maecenas fermentum gravida lorem non malesuada. Donec placerat nibh id commodo scelerisque. Curabitur turpis mauris, condimentum ut semper nec, porttitor sit amet nibh. Nulla tempor ullamcorper nisl vel gravida. Morbi ac nisi non neque viverra fermentum. Sed elementum sapien et urna accumsan tempor. Donec sit amet vehicula neque. Etiam porttitor diam at augue auctor ullamcorper. Nulla eget condimentum orci. Praesent eget mattis magna, ac accumsan nisi.
Nunc odio purus, maximus malesuada sagittis et, varius a ipsum. Nullam fermentum est eget orci dictum, eu placerat erat dictum. Vivamus a bibendum ante. Sed sit amet vulputate sapien. Donec varius, nisl pretium aliquet volutpat, nisl dolor interdum justo, in dictum quam est sit amet mauris. Integer a varius orci, non interdum ipsum. Mauris laoreet feugiat vestibulum. Morbi sit amet rhoncus ante. Cras feugiat orci dolor, id fringilla magna fringilla in. Integer ac est eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam gravida tristique pretium. Mauris quis nulla lacinia, imperdiet mi in, congue purus. Nam et lectus nec dolor dignissim ultrices ac blandit elit. Vestibulum pellentesque enim vitae metus sodales porttitor.
Fusce laoreet non ipsum quis sodales. Pellentesque mattis odio enim, eget tincidunt odio luctus ac. Donec dolor lectus, dapibus vitae dapibus quis, porttitor a dolor. Donec porttitor cursus ex ut luctus. Vivamus sed consequat mi. Nulla dapibus arcu dolor, in mollis enim sagittis a. Ut sed quam purus. Nunc a nunc sed ex accumsan lobortis. Sed sit amet tristique nulla. Curabitur sodales ante sit amet consequat semper. Donec gravida consequat mauris. Morbi maximus, enim et egestas dapibus, libero sem tincidunt lorem, sed laoreet leo libero eget elit. Pellentesque a erat eget sem bibendum imperdiet vitae ut augue. Donec luctus euismod tellus, ut pulvinar sapien scelerisque ut. In id consequat quam.
Nunc ante ex, tincidunt sit amet semper aliquet, auctor fermentum augue. Curabitur tincidunt, arcu ac finibus euismod, risus massa aliquet sem, placerat efficitur tellus nibh sed velit. Donec eleifend ante nec justo sollicitudin commodo. Aenean dapibus lectus sit amet nulla commodo, sed tempus dolor molestie. Proin eu sapien velit. Praesent mattis mi sed ante aliquam pharetra. Sed porttitor tellus ut ligula tristique tincidunt. Aenean sed lacinia purus, non tincidunt quam. Pellentesque at auctor ipsum, quis mattis tellus. Maecenas aliquet, dui vel suscipit commodo, neque eros sollicitudin lorem, et dapibus magna elit venenatis nulla. Ut aliquam nec nulla at dapibus. Aenean vestibulum elementum hendrerit. Morbi porttitor metus non lacus luctus mollis. Aliquam lectus lorem, tristique at dui id, gravida tincidunt velit.
Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed et lacinia ex, eu viverra nunc. Nullam eget fermentum sem. Mauris non ex eget quam lobortis auctor. Etiam venenatis malesuada sapien in volutpat. Etiam condimentum metus ut libero ultricies, ut venenatis purus placerat.
Aliquam nec ligula at est dapibus venenatis. Phasellus et nunc nec enim interdum iaculis in id mauris. Vestibulum nisi nisi, commodo vitae vestibulum ut, interdum lacinia nisi. Morbi pharetra magna quis hendrerit vehicula. Curabitur lacinia sodales lacinia. Curabitur pharetra purus at tellus rhoncus, eget posuere dolor ultrices. Duis id nibh sed libero fringilla tristique et tristique velit. In fermentum neque quis facilisis eleifend. Suspendisse et auctor quam. Fusce vel eros ac elit tempor commodo. Suspendisse sit amet tempus tortor. Nulla molestie et nulla quis vestibulum. Cras hendrerit dictum turpis. Vestibulum eros libero, commodo ut dignissim ut, laoreet at lacus.
Nunc posuere egestas nibh, at condimentum dolor blandit in. In elementum tellus massa, in molestie dui rutrum eget. Sed fermentum arcu vitae ante posuere, eget dignissim orci dignissim. Cras in ultrices urna. Sed nibh sapien, tempor sed fermentum ut, dictum a quam. Vestibulum neque odio, consectetur a mauris at, ultrices tristique enim. Cras vehicula nunc tincidunt diam facilisis cursus. Sed interdum, libero et scelerisque imperdiet, eros mi cursus dui, eget condimentum dui risus sollicitudin lectus. Etiam non turpis pretium, auctor dui sed, molestie justo. Proin eget quam sed odio sagittis porttitor. Vestibulum ornare leo justo, ut gravida eros facilisis eu. Sed luctus quam ac vestibulum blandit. Nam non ornare ex.`

const ContentContainer = ({currentContent}) => {
    
    const [inputText, setInputText] = useState("");
    
    return (
        <section id="content-container">
            {
                currentContent === 1 ?
                <Content1
                    setInputText={setInputText}
                />
                :
                <Content2
                    text={text}
                />
            }
            <div>{ inputText }</div>
        </section>
    )
};

export default ContentContainer;
